[unstable]
json-target-spec = true
build-std-features =["compiler-builtins-mem"]
panic-abort-tests = true
build-std = ["core", "compiler_builtins", "alloc"]

[target.x86_64-frostdos]
runner = "bootimage runner"

[build]
target ="x86_64-frostdos.json"
